mysql:
    image: mysql
    expose:
        - 3306
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    ports:
        - "3306:3306"

redis:
    image: redis
    expose:
        - 6379
    volumes:
        - ./apps/redis/redis-6379.conf:/usr/local/etc/redis.conf:ro
    ports:
        - "6379:6379"
    command: /usr/local/etc/redis.conf

nginx_php:
    build: ./apps/nginx_php
    volumes: 
        - ./config/vhosts:/etc/nginx/vhosts:ro
        - ./apps/nginx_php/php.ini:/usr/local/etc/php.ini
        - ./htdocs:/data/htdocs
        - ./logs:/data/logs
    environment:
        - XDEBUG_HOST
    links:
        - "mysql:mysql_service"
        - "redis:redis_service"
    expose:
        - 80
    ports:
        - "80:80"