mysql:
    image: mysql
    expose:
        - 3306
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    ports:
        - "3000:3306"

redis:
    image: redis
    expose:
        - 6379
    volumes:
        - ./apps/redis/redis-6379.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
        - "6379:6379"

nginx_php:
    build: ./apps/nginx_php
    volumes: 
        - ./config/vhosts:/etc/nginx/vhosts:ro 
        - ./htdocs:/data/htdocs
        - ./logs:/data/logs
    links:
        - "mysql:mysql_service"
        - "redis:redis_service"
    expose:
        - 80
    ports:
        - "8000:80"